### ISSUE TITLE
Python API - Stage Extension

### ISSUE THREAD

**Issue by cambel** [moveit/moveit_task_constructor#524]
Hi,

I am working on ROS Noetic.

I have tried to implement the Stage extension according to the [tutorial](https://ros-planning.github.io/moveit_task_constructor/howto.html#monitoringgenerator).

However, it fails with the following error:
```shell
Traceback (most recent call last):
  File "/root/osx-ur/catkin_ws/src/osx_examples/scripts/mtc_examples.py", line 265, in <module>
    main()
  File "/root/osx-ur/catkin_ws/src/osx_examples/scripts/mtc_examples.py", line 46, in main
    if task.plan(max_solutions=2):
  File "/root/osx-ur/catkin_ws/src/osx_examples/scripts/mtc_examples.py", line 258, in compute
    scene = self.upstream_solutions.pop(0).end.scene
TypeError: Unable to convert function return value to a Python type! The signature was
	(arg0: pymoveit_mtc.core.InterfaceState) -> planning_scene::PlanningScene
```
The issues seems to be the parsing of the PlanningScene.

I found unit tests for this in the `rostest_tampoline.py` but when running the tests with
```
rostest moveit_task_constructor_core rostest_mtc.test
```
The test fails because it can not find the library to import the PlanningScene
```
Traceback (most recent call last):
  File "/root/osx-ur/underlay_ws/src/moveit_task_constructor/core/python/test/rostest_trampoline.py", line 9, in <module>
    from moveit.core.planning_scene import PlanningScene
ModuleNotFoundError: No module named 'moveit.core'
```

Is is possible to extend Stages from the Python API?

**Comment by rhaschke** [comment]
> Is it possible to extend Stages from the Python API?

Yes, that should be possible. In your case, I guess the PlanningScene class is not yet wrapped in MoveIt. Try to use this branch: https://github.com/ros-planning/moveit/pull/2910
