### ISSUE TITLE
I encountered an error when building the sub package core of moveit_task_comstruct

### ISSUE THREAD

**Issue by czy1998916** [moveit/moveit_task_constructor#625]
I encountered an error when building the sub package core of moveit_task_comstruct.
The error is as follows
rx@rx:/opt/ros/humble/src/moveit_task_constructor$ cd core
rx@rx:/opt/ros/humble/src/moveit_task_constructor/core$ sudo -E bloom-generate rosdebian --os-name ubuntu --os-version jammy --ros-distro humble
==> Generating debs for ubuntu:jammy for package(s) ['moveit_task_constructor_core']
Could not resolve rosdep key 'moveit_task_constructor_msgs'
Try to resolve the problem with rosdep and then continue.
Continue [Y/n]? 
Running 'rosdep update'...
Could not resolve rosdep key 'moveit_task_constructor_msgs'
Try to resolve the problem with rosdep and then continue.
Continue [Y/n]? 
Running 'rosdep update'...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bloom/generators/common.py", line 198, in resolve_rosdep_key
    return resolve_more_for_os(key, view, installer, os_name, os_version)
  File "/usr/lib/python3/dist-packages/bloom/generators/common.py", line 113, in resolve_more_for_os
    d = view.lookup(rosdep_key)
  File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 204, in lookup
    return self.rosdep_defs[rosdep_name]
KeyError: 'moveit_task_constructor_msgs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bloom/generators/common.py", line 198, in resolve_rosdep_key
    return resolve_more_for_os(key, view, installer, os_name, os_version)
  File "/usr/lib/python3/dist-packages/bloom/generators/common.py", line 113, in resolve_more_for_os
    d = view.lookup(rosdep_key)
  File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 204, in lookup
    return self.rosdep_defs[rosdep_name]
KeyError: 'moveit_task_constructor_msgs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bloom/generators/common.py", line 96, in update_rosdep
    rosdep2.catkin_support.update_rosdep()
  File "/usr/lib/python3/dist-packages/rosdep2/catkin_support.py", line 95, in update_rosdep
    call(('rosdep', 'update'), pipe=PIPE)
  File "/usr/lib/python3/dist-packages/rosdep2/catkin_support.py", line 49, in call
    raise CalledProcessError(retcode, command)
subprocess.CalledProcessError: Command '('rosdep', 'update')' returned non-zero exit status 1.

Failed to update rosdep, did you run 'rosdep init' first?
![Image](https://github.com/user-attachments/assets/c8dd4e3c-a3e3-4312-b9e0-cdc5858e9c73)

Please tell me what the problem is. Thank you very much. It's urgent. My email is 1781113105@qq.com

**Comment by rhaschke** [comment]
What do you want to do? Building MTC? Building a .deb?
It's not recommended to modify /opt/ros directly. [Create your colcon workspace](https://docs.ros.org/en/foxy/Tutorials/Beginner-Client-Libraries/Creating-A-Workspace/Creating-A-Workspace.html) in your user folders.
When you want to build .deb files, you should run bloom-generate from the top-level folder, such that dependent packages can be build first.
